In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import KFold

In [2]:
col_names=['Marks1','Marks2','Admission']
ds=pd.read_csv("/home/ignis/Desktop/Student-University(For Logistic Regression Program).csv",header=None,names=col_names)
ds

Marks1     Marks2  Admission
0   34.623660  78.024693          0
1   30.286711  43.894998          0
2   35.847409  72.902198          0
3   60.182599  86.308552          1
4   79.032736  75.344376          1
..        ...        ...        ...
95  83.489163  48.380286          1
96  42.261701  87.103851          1
97  99.315009  68.775409          1
98  55.340018  64.931938          1
99  74.775893  89.529813          1

[100 rows x 3 columns]

In [3]:
x=ds.iloc[:,[0,1]].values
x

array([[34.62365962, 78.02469282],
       [30.28671077, 43.89499752],
       [35.84740877, 72.90219803],
       [60.18259939, 86.3085521 ],
       [79.03273605, 75.34437644],
       [45.08327748, 56.31637178],
       [61.10666454, 96.51142588],
       [75.02474557, 46.55401354],
       [76.0987867 , 87.42056972],
       [84.43281996, 43.53339331],
       [95.86155507, 38.22527806],
       [75.01365839, 30.60326323],
       [82.30705337, 76.4819633 ],
       [69.36458876, 97.71869196],
       [39.53833914, 76.03681085],
       [53.97105215, 89.20735014],
       [69.07014406, 52.74046973],
       [67.94685548, 46.67857411],
       [70.66150955, 92.92713789],
       [76.97878373, 47.57596365],
       [67.37202755, 42.83843832],
       [89.67677575, 65.79936593],
       [50.53478829, 48.85581153],
       [34.21206098, 44.2095286 ],
       [77.92409145, 68.97235999],
       [62.27101367, 69.95445795],
       [80.19018075, 44.82162893],
       [93.1143888 , 38.80067034],
       [61.83020602,

In [4]:
y=ds.iloc[:,2].values
y

array([0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1])

In [5]:
xp=preprocessing.scale(x)
xp

array([[-1.60224763,  0.63834112],
       [-1.82625564, -1.2075414 ],
       [-1.53903969,  0.3612943 ],
       [-0.28210129,  1.0863683 ],
       [ 0.69152826,  0.49337794],
       [-1.06199728, -0.5357394 ],
       [-0.23437234,  1.63818413],
       [ 0.4845113 , -1.06373024],
       [ 0.53998666,  1.14651105],
       [ 0.97044832, -1.22709853],
       [ 1.56075461, -1.51418452],
       [ 0.48393864, -1.92641626],
       [ 0.86065022,  0.55490359],
       [ 0.1921582 ,  1.70347834],
       [-1.34839922,  0.53082781],
       [-0.60293429,  1.24314792],
       [ 0.17694982, -0.72913975],
       [ 0.11893077, -1.05699346],
       [ 0.25914553,  1.44433023],
       [ 0.58543944, -1.00845873],
       [ 0.0892403 , -1.26468472],
       [ 1.2413042 , -0.02285779],
       [-0.78042096, -0.93923898],
       [-1.62350714, -1.19053019],
       [ 0.63426559,  0.14875155],
       [-0.17423248,  0.20186768],
       [ 0.75131151, -1.15742514],
       [ 1.41886056, -1.4830648 ],
       [-0.19700066,

In [6]:
kf=KFold(n_splits=5)
kf

KFold(n_splits=5, random_state=None, shuffle=False)

In [7]:
for train_index,test_index in kf.split(xp):
    xtrain,xtest,ytrain,ytest=train_test_split(xp,y,test_size=0.20,random_state=0)
    x1=xtrain[:,0]
    x2=xtrain[:,1]
    b0=0.0
    b1=0.0
    b2=0.0
    epoch=10000
    alpha=0.001
    while(epoch>0):
        for i in range(len(xtrain)):
            prediction=1/(1+np.exp(-(b0+b1*x1[i]+b2*x2[i])))
            b0=b0+alpha*(ytrain[i]-prediction)*prediction*(1-prediction)*1.0
            b1=b1+alpha*(ytrain[i]-prediction)*prediction*(1-prediction)*x1[i]
            b2=b2+alpha*(ytrain[i]-prediction)*prediction*(1-prediction)*x2[i]
            epoch=epoch-1

In [8]:
print(b0)
print(b1)
print(b2)

0.16701973288386185
0.4868177427484465
0.4948075155845019


In [9]:
final_prediction=[]
x3=xtest[:,0]
x4=xtest[:,1]
print(ytest)
print(xtest[:,0],xtest[:,1])

[1 0 0 0 1 1 1 1 0 1 0 0 0 1 1 1 0 1 1 1]
[ 0.75131151 -1.21735452 -1.53903969 -0.82939191  1.76561835  0.45703019
  0.17694982 -0.26788246 -0.79324552  0.92170742 -1.60736862 -0.52488391
 -0.26800278  0.1921582   0.4845113  -0.22029098 -0.78042096  0.63426559
 -0.70239602  0.53998666] [-1.15742514  0.68269533  0.3612943  -0.34684551  0.33247025  1.00722043
 -0.72913975  0.37172177 -0.88792768 -0.96495748 -0.31507682 -1.65775547
 -1.28253412  1.70347834 -1.06373024  0.35619356 -0.93923898  0.14875155
  0.1736574   1.14651105]


In [10]:
y_pred=[0]*len(xtest)
for i in range(len(xtest)):
    y_pred[i]=np.round(1/(1+np.expprint(final_prediction)(-(b0+b1*x3[i]+b2*x4[i]))))
    final_prediction.append(np.ceil(y_pred[i]))

In [11]:
print(final_prediction)

[0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0]


In [12]:
from sklearn.metrics import accuracy_score
print("Accuracy",accuracy_score(ytest,y_pred))


Accuracy 0.8
